java_library(
    name = "runner-2.11",
    srcs = ["Runner.java"],
    visibility = ["//visibility:public"],
    deps = [
        "@scala_2_11//:org_scalatest_scalatest_2_11",
        "@bazel_tools//tools/java/runfiles",
    ],
)

java_library(
    name = "runner-2.12",
    srcs = ["Runner.java"],
    visibility = ["//visibility:public"],
    deps = [
        "@scala_2_12//:org_scalatest_scalatest_2_12",
        "@bazel_tools//tools/java/runfiles",
    ],
)
