package(default_visibility = ["//visibility:public"])

load("//scala:scala_import.bzl", "scala_import")

scala_import(
    name = "scalatest-2.11",
    jars = [],
    exports = [
        "@scala_2_11//:org_scalatest_scalatest_2_11",
        "@scala_2_11//:org_scalactic_scalactic_2_11",
    ],
)

scala_import(
    name = "scalatest-2.12",
    jars = [],
    exports = [
        "@scala_2_12//:org_scalatest_scalatest_2_12",
        "@scala_2_12//:org_scalactic_scalactic_2_12",
    ],
)
